# Generated by Django 5.1.4 on 2024-12-27 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=600)),
                ('bid_value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)])),
                ('categories', models.CharField(choices=[('1', 'Art'), ('2', 'Electronics'), ('3', 'Fashion'), ('4', 'Household item'), ('5', 'Jewelries'), ('6', 'Treats')], max_length=20)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
