# Generated by Django 5.1.4 on 2024-12-29 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_product_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
