# Generated by Django 5.1.4 on 2024-12-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
