# Generated by Django 5.1.4 on 2025-01-02 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_product_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='ListingWatchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
