# Generated by Django 5.1.4 on 2025-01-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_product_watchlist_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_bidder',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
