# Generated by Django 5.1.4 on 2025-01-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_product_current_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_bidder',
            field=models.CharField(default=' No one has made a bid yet', max_length=150),
        ),
    ]
