# Generated by Django 5.1.4 on 2025-01-02 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_product_current_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_bidder',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('product_comment', models.CharField(max_length=600)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
