# Generated by Django 5.1.4 on 2025-01-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_bidder',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
